### ISSUE TITLE
Language Support 

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/flutter_thingsboard_pe_app#124]
Thingsboard PE moile app 
On things board I have the user able to change the language and have the dashboards change accordingly, 
On the app I see there is support for localization, is there a way to have the user pick the language on the app or have the language automatically picked up from when the user logs in or opens mobile app. The app uses keywords like home, login, email etc which should be converted to the default language that the login account is set to on the cloud. 

Any assistance to explain the flow of how the language mechanism works with the app would be appreciated :)

**Comment by ybeshkarov** [comment]
Hello @Mark-MV-Wizard,

App localization is determined by the phone's locale settings. If the user's phone locale matches one of the supported locales, texts like "Home," "Login," etc., will be translated accordingly. Otherwise, the app will default to English.

Technically, it’s possible to localize the app based on the locale selected on the platform, but this feature is not currently implemented.
