### ISSUE TITLE
Getting Error in More Page, when reopening the app. 

### ISSUE THREAD

**Issue by ronit18** [thingsboard/flutter_thingsboard_pe_app#78]
I am currently using the latest code for my android app. And in that i have configured Notifications. It was working perfectly (Notifications page and notification count bubble). After the latest code, i am not seeing any notifications in notifications page. I am seeing a notification in my noitication center (Phone's). 

![WhatsApp Image 2024-04-04 at 11 14 05 AM](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/69378341/ceff75d0-471c-4545-9698-594afc32a554)

**Comment by ybeshkarov** [comment]
Hello @ronit18,

Previously, notifications were stored locally on the phone, but this approach led to some issues. Therefore, we've reworked the system to retrieve notifications from the backend instead. However, due to the backend part not being updated and lacking several endpoints, you're currently unable to access your notifications.

We apologize for the inconvenience. We're confident the backend will be updated soon, and you'll be able to access your notifications.
